import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { api } from "~/utils/api";
import { TodoList } from "../components/TodoList";
import { TodoForm } from "../components/TodoForm";
import { useState } from "react";

export default function Home() {
  const [content, setContent] = useState("");
  const ctx = api.useContext();

  const { mutate: createMutation } = api.todo.create.useMutation({
    onSettled: async () => {
      setContent("");
      await ctx.todo.getAll.invalidate();
    },
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="m-auto flex min-h-screen max-w-[700px] flex-col items-center">
        <AuthShowcase />
        <h1 data-testid="website-title" className="text-2xl">
          Home Page
        </h1>
        <TodoForm
          formSubmission={createMutation}
          setContent={setContent}
          content={content}
        />
        <TodoList />
      </main>
    </>
  );
}

function AuthShowcase() {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl ">
        {sessionData && <span>Logged in</span>}
      </p>
      <button
        className="rounded-full  px-10 py-3 font-semibold no-underline transition "
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
}
